name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: [stable]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Check code
      run: cargo check
      
    - name: Run tests
      run: cargo test
      
    - name: Build
      run: cargo build --release
      
    - name: Upload macOS binary
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: boxdrop-sync-daemon-macos
        path: target/release/boxdrop-sync-daemon
        retention-days: 30 